package com.youle.gamebox.ui.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JSON_ENTRY.
 */
public class JsonEntry {

    private Long resouce;
    private String json;

    public JsonEntry() {
    }

    public JsonEntry(Long resouce) {
        this.resouce = resouce;
    }

    public JsonEntry(Long resouce, String json) {
        this.resouce = resouce;
        this.json = json;
    }

    public Long getResouce() {
        return resouce;
    }

    public void setResouce(Long resouce) {
        this.resouce = resouce;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

}
