package com.youle.gamebox.ui.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOG_USER.
 */
public class LogUser {

    private String userName;
    private String password;
    private String option;
    private String isdel;
    private Long lastLogin;

    public LogUser() {
    }

    public LogUser(String userName) {
        this.userName = userName;
    }

    public LogUser(String userName, String password, String option, String isdel, Long lastLogin) {
        this.userName = userName;
        this.password = password;
        this.option = option;
        this.isdel = isdel;
        this.lastLogin = lastLogin;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getOption() {
        return option;
    }

    public void setOption(String option) {
        this.option = option;
    }

    public String getIsdel() {
        return isdel;
    }

    public void setIsdel(String isdel) {
        this.isdel = isdel;
    }

    public Long getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(Long lastLogin) {
        this.lastLogin = lastLogin;
    }

}
