package com.youle.gamebox.ui.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.youle.gamebox.ui.greendao.LogUser;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LOG_USER.
*/
public class LogUserDao extends AbstractDao<LogUser, String> {

    public static final String TABLENAME = "LOG_USER";

    /**
     * Properties of entity LogUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property UserName = new Property(0, String.class, "userName", true, "USER_NAME");
        public final static Property Password = new Property(1, String.class, "password", false, "PASSWORD");
        public final static Property Option = new Property(2, String.class, "option", false, "OPTION");
        public final static Property Isdel = new Property(3, String.class, "isdel", false, "ISDEL");
        public final static Property LastLogin = new Property(4, Long.class, "lastLogin", false, "LAST_LOGIN");
    };


    public LogUserDao(DaoConfig config) {
        super(config);
    }
    
    public LogUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LOG_USER' (" + //
                "'USER_NAME' TEXT PRIMARY KEY NOT NULL ," + // 0: userName
                "'PASSWORD' TEXT," + // 1: password
                "'OPTION' TEXT," + // 2: option
                "'ISDEL' TEXT," + // 3: isdel
                "'LAST_LOGIN' INTEGER);"); // 4: lastLogin
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LOG_USER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LogUser entity) {
        stmt.clearBindings();
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(1, userName);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(2, password);
        }
 
        String option = entity.getOption();
        if (option != null) {
            stmt.bindString(3, option);
        }
 
        String isdel = entity.getIsdel();
        if (isdel != null) {
            stmt.bindString(4, isdel);
        }
 
        Long lastLogin = entity.getLastLogin();
        if (lastLogin != null) {
            stmt.bindLong(5, lastLogin);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LogUser readEntity(Cursor cursor, int offset) {
        LogUser entity = new LogUser( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // userName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // password
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // option
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // isdel
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // lastLogin
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LogUser entity, int offset) {
        entity.setUserName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPassword(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOption(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsdel(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLastLogin(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(LogUser entity, long rowId) {
        return entity.getUserName();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(LogUser entity) {
        if(entity != null) {
            return entity.getUserName();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
