package com.youle.gamebox.ui.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.youle.gamebox.ui.greendao.RecommendGame;
import com.youle.gamebox.ui.greendao.JsonEntry;
import com.youle.gamebox.ui.greendao.LogUser;
import com.youle.gamebox.ui.greendao.GameBean;
import com.youle.gamebox.ui.greendao.UserInfo;

import com.youle.gamebox.ui.greendao.RecommendGameDao;
import com.youle.gamebox.ui.greendao.JsonEntryDao;
import com.youle.gamebox.ui.greendao.LogUserDao;
import com.youle.gamebox.ui.greendao.GameBeanDao;
import com.youle.gamebox.ui.greendao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recommendGameDaoConfig;
    private final DaoConfig jsonEntryDaoConfig;
    private final DaoConfig logUserDaoConfig;
    private final DaoConfig gameBeanDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final RecommendGameDao recommendGameDao;
    private final JsonEntryDao jsonEntryDao;
    private final LogUserDao logUserDao;
    private final GameBeanDao gameBeanDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recommendGameDaoConfig = daoConfigMap.get(RecommendGameDao.class).clone();
        recommendGameDaoConfig.initIdentityScope(type);

        jsonEntryDaoConfig = daoConfigMap.get(JsonEntryDao.class).clone();
        jsonEntryDaoConfig.initIdentityScope(type);

        logUserDaoConfig = daoConfigMap.get(LogUserDao.class).clone();
        logUserDaoConfig.initIdentityScope(type);

        gameBeanDaoConfig = daoConfigMap.get(GameBeanDao.class).clone();
        gameBeanDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        recommendGameDao = new RecommendGameDao(recommendGameDaoConfig, this);
        jsonEntryDao = new JsonEntryDao(jsonEntryDaoConfig, this);
        logUserDao = new LogUserDao(logUserDaoConfig, this);
        gameBeanDao = new GameBeanDao(gameBeanDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(RecommendGame.class, recommendGameDao);
        registerDao(JsonEntry.class, jsonEntryDao);
        registerDao(LogUser.class, logUserDao);
        registerDao(GameBean.class, gameBeanDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        recommendGameDaoConfig.getIdentityScope().clear();
        jsonEntryDaoConfig.getIdentityScope().clear();
        logUserDaoConfig.getIdentityScope().clear();
        gameBeanDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
    }

    public RecommendGameDao getRecommendGameDao() {
        return recommendGameDao;
    }

    public JsonEntryDao getJsonEntryDao() {
        return jsonEntryDao;
    }

    public LogUserDao getLogUserDao() {
        return logUserDao;
    }

    public GameBeanDao getGameBeanDao() {
        return gameBeanDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
