package com.youle.gamebox.ui.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.youle.gamebox.ui.greendao.JsonEntry;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table JSON_ENTRY.
*/
public class JsonEntryDao extends AbstractDao<JsonEntry, Long> {

    public static final String TABLENAME = "JSON_ENTRY";

    /**
     * Properties of entity JsonEntry.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Resouce = new Property(0, Long.class, "resouce", true, "RESOUCE");
        public final static Property Json = new Property(1, String.class, "json", false, "JSON");
    };


    public JsonEntryDao(DaoConfig config) {
        super(config);
    }
    
    public JsonEntryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'JSON_ENTRY' (" + //
                "'RESOUCE' INTEGER PRIMARY KEY ," + // 0: resouce
                "'JSON' TEXT);"); // 1: json
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'JSON_ENTRY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, JsonEntry entity) {
        stmt.clearBindings();
 
        Long resouce = entity.getResouce();
        if (resouce != null) {
            stmt.bindLong(1, resouce);
        }
 
        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(2, json);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public JsonEntry readEntity(Cursor cursor, int offset) {
        JsonEntry entity = new JsonEntry( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // resouce
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // json
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, JsonEntry entity, int offset) {
        entity.setResouce(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJson(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(JsonEntry entity, long rowId) {
        entity.setResouce(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(JsonEntry entity) {
        if(entity != null) {
            return entity.getResouce();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
